### ISSUE TITLE
bfasst can't run without rapidwright

### ISSUE THREAD

**Issue by jgoeders** [byuccl/bfasst#113]
Since the physical netlist script imports from rapidwright, it's not currently possible to use run_design.py without having rapidwright installed.  It would be nice to have a workaround to remove this dependency.

**Comment by dallinjdahl** [comment]
We could do something like this: https://stackoverflow.com/a/3496790

**Comment by reillymck** [comment]
Also, this is something that would be appropriate for the __init__.py file.

**Comment by dallinjdahl** [comment]
We could also refactor the flows file and load the relevant one when asked.  Then it would automatically report an error if we needed rapidwright, but if not, it would run just fine...

**Comment by reillymck** [comment]
I really like Dallin's idea. The way I understand it, is we would move the imports so that they are inside the relevant function calls. So the import happens when the function is called, not when the run_design is loaded. That is what you are suggesting correct?

**Comment by jgoeders** [comment]
That sounds like the best approach to me.

________________________________

**Comment by dallinjdahl** [comment]
That's basically the gist :)
