### ISSUE TITLE
CI fails with java.lang.RuntimeException: ERROR: Failed to reliably download file

### ISSUE THREAD

**Issue by jgoeders** [byuccl/bfasst#154]
The CI fails about half the time with an error downloading a file.
For example:
```
java.lang.RuntimeException: ERROR: Failed to reliably download file: data/devices/artix7/xc7a200t_db.dat
```

This happens while running experiments, not setting up the environment, which is unexpected, because the Rapidwright files are downloaded during environment setup.  Not sure why files would be downloaded during the experiment run.

**Comment by reillymck** [comment]
It appears that rapidwright only downloads the database for parts when you use them for the first time instead of downloading all of them at install...

**Comment by jgoeders** [comment]
Can we force it to download a specific part and retry on failure?

**Comment by reillymck** [comment]
I made an adjustment in ooc in the run_rapidwright function in xilinx_phys_netlist:
```
        try:
            self.rw_design = Design.readCheckpoint(
                design.xilinx_impl_checkpoint_path, design.impl_edif_path
            )
        except jpype.JException as exc:
            error = str(exc)
            if "Failed to reliably download file" in error:
                self.rw_design = Design.readCheckpoint(
                design.xilinx_impl_checkpoint_path, design.impl_edif_path
            )
            else:
                raise RapidwrightException(str(exc))
```
This will try and second time. What do you think?

**Comment by reillymck** [comment]
Or do we want to edit the make file so it downloads the database during install? Not sure how to do that, but I can look into it.

**Comment by jgoeders** [comment]
Yeah this looks like a good start.

I agree during setup would be better. Or in https://github.com/byuccl/bfasst/blob/main/bfasst/jpype_jvm.py

________________________________

**Comment by jgoeders** [comment]
https://github.com/Xilinx/RapidWright/issues/669

**Comment by jgoeders** [comment]
The issue was due to running jobs in parallel -- the files were trying to be downloaded by multiple instances of rapidwright simultaneously.
