### ISSUE TITLE
Add error injector script to test physical netlist / struct compare

### ISSUE THREAD

**Issue by jgoeders** [byuccl/bfasst#205]
Current physical netlist + structural compare flow: https://github.com/byuccl/bfasst/blob/cb2aeaede2cd5f161fadfa134b07dcdbbea1aab2/bfasst/flows.py#L191

We would like a new flow that follows all of these same steps, except that before structural compare, it takes the "reversed" netlist (the one produced by `xray_rev`) and injects some modification before passing it to the structural comparison.  

We would then want to repeat this injection many times (say 100 times) injecting a different random modification each time.

Injection types:
  * Pick random LUT, flip random bit in INIT
  * Pick random instance input pin and drive it from another random wire

These random choices should be seeded by a hard-coded value (could be overridden by command line flow argument), such that the chosen injection points are deterministic (ie repeatable)

**Comment by jgoeders** [comment]
Injection types:
  * Pick random LUT, flip random bit in INIT
  * Pick random instance input pin and drive it from another random wire

**Comment by jgoeders** [comment]
@KeenanRileyFaulkner I think it makes sense to put the new error injector tool in the `transform` folder.  I know the previous error injector tools was in it's own `error_injection` folder, but I don't think that's necessary.  

As we talked about, we may just want to remove the old error injector tool (and it's parent folder)

**Comment by KeenanRileyFaulkner** [comment]
Closed by #212
