### ISSUE TITLE
Rename `ninja_tools` and `ninja_flows` to just `tools` and `flows`.  Create `_legacy` for older tools/flows

### ISSUE THREAD

**Issue by jgoeders** [byuccl/bfasst#315]

**Comment by KeenanRileyFaulkner** [comment]
Do I need to try to keep things in _legacy working, or is simply moving them enough? I've been deleting the old flows as I've brought them up to speed with ninja

**Comment by yonnorc42** [comment]
@jgoeders Do you still want this done? Would ninja_utils be renamed as well?

**Comment by jgoeders** [comment]
@yonnorc42 Yes, it would be good to do this.  

>Would ninja_utils be renamed as well?
Yes.

**Comment by jgoeders** [comment]
Fixed by #381

**Comment by jgoeders** [comment]
> Do we want to combine `bfasst/utils` and `bfasst/ninja_utils`? Or no?

Yes. I'll re-open this.

**Comment by yonnorc42** [comment]
@KeenanRileyFaulkner Which tools are the legacy tools?

**Comment by KeenanRileyFaulkner** [comment]
Anything not imported into the current flows. I think that all the non-legacy tools are inside the `tools` directory and all the legacy ones are outside it. You might double check that though

**Comment by KeenanRileyFaulkner** [comment]
https://github.com/byuccl/bfasst/blob/main/bfasst/synth/vivado.py

**Comment by KeenanRileyFaulkner** [comment]
Most of the direct children of the `bfasst/` directory in the project are currently legacy tools. For example, everything in `bfasst/synth`, `bfasst/compare`, `bfasst/impl`, `bfasst/netlist_mapping`, `bfasst/opt`, `bfasst/reverse_bit`, and the `tool.py` file in `bfasst/`.
