### ISSUE TITLE
Some Phys Netlist Cmp designs do not work with Vivado 2023.2

### ISSUE THREAD

**Issue by reillymck** [byuccl/bfasst#334]
See designs here: https://github.com/byuccl/bfasst/blob/main/experiments/xilinx_phys_netlist_cmp.yaml

**Comment by yonnorc42** [comment]
Failing Designs:

bubblesort:
20240119164937 FAIL: Not equivalent. CLBLM_R_X3Y84_SLICE_X2Y84_A6SRL has no possible match in the netlist.

pwm:
20240119172208 Equivalence questionable
20240119172208 FAIL: Warnings during equivalence verification

quadratic_func:
20240119172445 FAIL: Not equivalent. CLBLL_L_X2Y125_SLICE_X0Y125_CARRY4 has no possible match in the netlist.

simon_core:
20240119172952 FAIL: Not equivalent. CLBLM_R_X3Y105_SLICE_X2Y105_A6SRL has no possible match in the netlist.

raygentop:
20240119174621 FAIL: Not equivalent. CLBLM_R_X3Y109_SLICE_X2Y109_A6SRL has no possible match in the netlist.

mkSMAdapter48 error:
FAILED: /home/yonnorc42/bfasst/build/vtr_benchmarks/mkSMAdapter4B/struct_cmp/struct_cmp.log
python bfasst/utils/structural.py --build_dir /home/yonnorc42/bfasst/build/vtr_benchmarks/mkSMAdapter4B --netlists /home/yonnorc42/bfasst/build/vtr_benchmarks/mkSMAdapter4B/netlist_cleanup/mkSMAdapter4B_random_clean.v /home/yonnorc42/bfasst/build/vtr_benchmarks/mkSMAdapter4B/vivado_phys_netlist/viv_impl_physical.v --log_path /home/yonnorc42/bfasst/build/vtr_benchmarks/mkSMAdapter4B/struct_cmp/struct_cmp.log
Traceback (most recent call last):
  File "/home/yonnorc42/bfasst/bfasst/utils/structural.py", line 775, in <module>
    struct_cmp.compare_netlists()
  File "/home/yonnorc42/bfasst/bfasst/utils/structural.py", line 175, in compare_netlists
    self.perform_mapping()
  File "/home/yonnorc42/bfasst/bfasst/utils/structural.py", line 415, in perform_mapping
    self.potential_mapping_wrapper(next(instance_iter))
  File "/home/yonnorc42/bfasst/bfasst/utils/structural.py", line 340, in potential_mapping_wrapper
    instances_matching = self.check_for_potential_bram_mapping(instance)
  File "/home/yonnorc42/bfasst/bfasst/utils/structural.py", line 581, in check_for_potential_bram_mapping
    named_instance.properties["RAM_EXTENSION_A"] == '"NONE"'
KeyError: 'RAM_EXTENSION_A'
ninja: build stopped: subcommand failed.
ERROR: Ninja failed with return code 1
