### ISSUE TITLE
Weekly Tests failing

### ISSUE THREAD

**Issue by KeenanRileyFaulkner** [byuccl/bfasst#338]
The weekly tests have never successfully passed for a variety of issues surrounding #245. The current one is that the bfasst script is missing the `.py` extension in `.github/workflows/weeklytests.yml`:
[see here](https://github.com/byuccl/bfasst/actions/runs/6520729198/job/17708572058#step:5:7)

**Comment by jgoeders** [comment]
@KeenanRileyFaulkner Isn't it missing the .py extension?

**Comment by KeenanRileyFaulkner** [comment]
@jgoeders Yes, it's a one line fix. This could be a good first issue for @yonnorc42, or I can fix it if he's got other stuff to do.
