### ISSUE TITLE
CI brings in all submodules, but often doesn't need to

### ISSUE THREAD

**Issue by jgoeders** [byuccl/bfasst#341]
Can we bring in fewer submodules in the CI when they are not needed?

Perhaps using this approach:
```
git submodule init <submodule a> <submodule b>
```

**Comment by yonnorc42** [comment]
@jgoeders Would this need to be approached differently because of some of the changes that you've made recently?

**Comment by jgoeders** [comment]
@yonnorc42 

I didn't really have a plan for this.  Different tests require different tools.  For example, I think only one tool requires yosys, but we spend quite a bit of time setting it up for every test.  We don't have a mechanism for conveying what tools are needed from the test up to the environment setup.  I don't have any good ideas on how to do this.  Maybe others have thoughts? @dallinjdahl @KeenanRileyFaulkner @reillymck

**Comment by reillymck** [comment]
I was thinking we could make recipes for different unit tests and instead of make install it makes the test-specific recipe.

**Comment by jgoeders** [comment]
I was thinking more along the lines of having something like this in the yaml files:

```yaml
tools: vivado yosys rapidwright
```

And then the environment setup code could iterate through these and call `make install_yosys`, `make install_rapidwright`, etc.

**Comment by jgoeders** [comment]
I've started working on this in the linked PR; however, I think the correct way to do this would be to have the tools listed in the yaml that details all flows (discussed in #362 and #382), rather than in the test yaml file.

**Comment by KeenanRileyFaulkner** [comment]
I've been working on that yaml file, and will add this functionality.
