### ISSUE TITLE
Weekly tests failing

### ISSUE THREAD

**Issue by jgoeders** [byuccl/bfasst#351]

**Comment by jgoeders** [comment]
https://github.com/byuccl/bfasst/blob/main/.github/workflows/unittests.yml#L49

**Comment by KeenanRileyFaulkner** [comment]
This issue is not resolved. See [weekly tests run 25](https://github.com/byuccl/bfasst/actions/runs/6992178706)

**Comment by yonnorc42** [comment]
That pull request should fix it. I had to add the private gmt_tools key in another location I missed the first time.

**Comment by KeenanRileyFaulkner** [comment]
This is still an issue

**Comment by yonnorc42** [comment]
Weekly tests are still failing because of failing to clone gmt_tools on the runners @jgoeders

**Comment by jgoeders** [comment]
This needs to be removed: https://github.com/byuccl/bfasst/blob/main/.github/workflows/weeklytests.yml#L45

And the specific tools that are needed will need to be installed like [here](https://github.com/byuccl/bfasst/blob/main/.github/workflows/unittests.yml#L98) or [here](https://github.com/byuccl/bfasst/blob/main/.github/workflows/unittests.yml#L56)
