### ISSUE TITLE
Shorten run-experiments name

### ISSUE THREAD

**Issue by jgoeders** [byuccl/bfasst#369]
The names used in the CI are too long and get cut off -- it's hard to see which run is failing without hovering over them:

<img width="269" alt="image" src="https://github.com/byuccl/bfasst/assets/1851142/68826881-b408-41ce-965b-5b2de5ab1ce4">

**Comment by yonnorc42** [comment]
@jgoeders Do you have a specific name change in mind?

**Comment by jgoeders** [comment]
How about we shorten the CI name `run-experiments` to `run-test`

And for the directory structure, lets rename `experiments/tests/` to `tests/ci/`

**Comment by yonnorc42** [comment]
There's already a directory called `test/` Is that going to be confusing if there's another directory called `tests/` at the same level?
