### ISSUE TITLE
Add NetlistCleanupTool to Structural Error Injection flow

### ISSUE THREAD

**Issue by KeenanRileyFaulkner** [byuccl/bfasst#394]

**Comment by jgoeders** [comment]
@KeenanRileyFaulkner @yonnorc42 What's the motivation for this?  While it's probably good to have, it doesn't look like the CI tests are failing without it.  Is that correct?

**Comment by KeenanRileyFaulkner** [comment]
Right, it was something we talked about in our meeting on Monday I think. @jgoeders 
If we don't want to do it, that's fine. I came away thinking we did, though.
