### ISSUE TITLE
Xray Dependency on part database

### ISSUE THREAD

**Issue by jgoeders** [byuccl/bfasst#415]
I ran into an interesting issue where I deleted my fasm2bels and then ran `make install_fasm2bels` to reinstall it.  At the end of the install steps it runs a flow to regenerate the part database; however, since I had run the flow previously, I got `ninja: no work to do.`

The `XRay` tool should probably be updated to add the part database as a dependency so that ninja throws an error if the file does not exist.

**Comment by yonnorc42** [comment]
@jgoeders To guarantee that you don't get `ninja: no work to do.`, could we just add 
```
mv build build_temp
python scripts/run.py VivadoBitToNetlist designs/basic/and3 --no_tool_checks
rm -r build
mv build_temp build
```
to the install_fasm2bels.sh to guarantee that the flow runs and the database is generated?
