### ISSUE TITLE
Unittest has long run time.  Move long running tests to existing tests.

### ISSUE THREAD

**Issue by jgoeders** [byuccl/bfasst#421]
Unittest takes a long time to run.  This is mainly due to the tests that run the flows, then invoke ninja again to make sure there's no work to do.  This is a good test, but we could move this extra check to our other tests that run the flows.  At the end of running the CI yaml file, it could have another step that runs ninja to make sure there's no work to do.

**Comment by yonnorc42** [comment]
@jgoeders I'm a little bit confused by this. Isn't the reason that unittest takes so long is because some of the flows like VivadoBitAnalysis just take a long time to run? Does invoking ninja again really affect the runtime that much?

**Comment by jgoeders** [comment]
<img width="224" alt="image" src="https://github.com/byuccl/bfasst/assets/1851142/a3674008-994a-4b90-b7bb-0b095e508419">

The idea is that we don't need unittests (the first one in that pic) to run the full end-to-end flows, because they are already being run by the "run-test" tests.  So we can remove those end-to-end tests from unittests.  However, the functionality that checks that ninja doesn't have any more work to do is a nice check, but we could move it to the end of the "run-test" CI.

Does that make sense?

**Comment by yonnorc42** [comment]
Yes that does make sense. So would you add this functionality in the unittests.yml file under the run-test job?

**Comment by jgoeders** [comment]
Yes, exactly.  I'm not sure what that would look like.  If you can't do it from a set of bash commands, you may need a separate python script.

**Comment by yonnorc42** [comment]
@jgoeders I added this into the update unittests pull request. Let me know if you want me to change how it's implemented.
