### ISSUE TITLE
Redundant unittests?

### ISSUE THREAD

**Issue by reillymck** [byuccl/bfasst#476]
https://github.com/byuccl/bfasst/blob/main/test/flows/test_vivado_flow.py#L46
https://github.com/byuccl/bfasst/blob/main/test/scripts/test_ninja_flow_manager.py#L95

These two seem to be doing the same thing (and the same for every file in test/flows). Maybe I'm missing something?

**Comment by reillymck** [comment]
Both files are being ran though. Total overlap between them should be investigated.

**Comment by yonnorc42** [comment]
Yeah I think you're right, they seem to do the same thing. But for the same flow, Vivado, why does one of them have the expected number of build statements at 5, and for the other, 6?

**Comment by reillymck** [comment]
I'm not sure, but as I've been running the unit tests for my pr, it seems that not all of the redundant ones run. It looked like possible hanging code.
