### ISSUE TITLE
Improper function calls

### ISSUE THREAD

**Issue by reillymck** [byuccl/bfasst#64]
In the [file flows.py](/scripts/bfasst/flows.py) there are several calls to bfasst.compare.conformal.Conformal_CompareTool() without specifying a vendor. From what I can tell, Vendor is a required arg. This happens on line 98, 261, 341, and 381. (For commit [742bfe2](https://github.com/byuccl/bfasst/commit/742bfe225c5e8153b26b72d257ec48ae64dae14c)). Am I missing something?

**Comment by jgoeders** [comment]
You're probably not missing anything.  Just a lack of CI :)

**Comment by reillymck** [comment]
Add vendor to compare args.

**Comment by reillymck** [comment]
Closed in PR #70
