### ISSUE TITLE
print_to_stdout inconsistent

### ISSUE THREAD

**Issue by reillymck** [byuccl/bfasst#66]
It seems that run_design.py and run_experiment.py pass `bool print_to_stdout` to the `flow_fcn()`. Not all flow functions accept this parameter. Also, is this parameter needed? Maybe multi-threading could be edited to always print each thread to a different file and never to stdout (not sure why you would want all the threads printing to stdout). Otherwise, if the user does not want the results of the run then they should use `>>` to redirect stdout to a file.

**Comment by jgoeders** [comment]
I agree. Sound good!

**Comment by reillymck** [comment]
Resolved in PR #70
