### ISSUE TITLE
Caedm/compile_results.py uses Python2?

### ISSUE THREAD

**Issue by reillymck** [byuccl/bfasst#71]
Is this [file](https://github.com/byuccl/bfasst/blob/master/scripts/caedm/compile_results.py) supposed to use python2? The #! and the print call seems to suggest so. Any reason why it can't be ran in python3?

**Comment by reillymck** [comment]
I also see a lot of other caedm .py files use python2. Also wondering about the following:
- scripts/conformal/compile_results.py:97:15
- scripts/conformal/generateDofile.py
- scripts/iCEcube2/constrainOptimizer.py

**Comment by jgoeders** [comment]
We don't use these files.  They can be deleted.

**Comment by reillymck** [comment]
Closed in pr #73
